2024-05-10T21:51:51.691+0500	ERROR	v1/user.go:119	failed to list users	{"error": "rpc error: code = Unknown desc = ERROR: relation \"users\" does not exist (SQLSTATE 42P01)"}
dennic_api_gateway/api/handlers/v1.(*HandlerV1).ListUsers
	/home/bobo/go/src/dennic_api_gateway/api/handlers/v1/user.go:119
github.com/gin-gonic/gin.(*Context).Next
	/home/bobo/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
dennic_api_gateway/api.NewRoute.NewAuthorizer.func2
	/home/bobo/go/src/dennic_api_gateway/api/middleware/casbin/casbin.go:30
github.com/gin-gonic/gin.(*Context).Next
	/home/bobo/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
dennic_api_gateway/api.NewRoute.GinTracing.func1
	/home/bobo/go/src/dennic_api_gateway/api/middleware/tracing.go:31
github.com/gin-gonic/gin.(*Context).Next
	/home/bobo/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/bobo/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/bobo/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/bobo/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
	/home/bobo/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/bobo/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/bobo/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
	/snap/go/10585/src/net/http/server.go:3137
net/http.(*conn).serve
	/snap/go/10585/src/net/http/server.go:2039
2024-05-10T21:52:03.150+0500	INFO	app/main.go:41	api gateway service stops
2024-05-10T21:52:03.150+0500	ERROR	app/main.go:32	app run	{"error": "http: Server closed"}
main.main.func1
	/home/bobo/go/src/dennic_api_gateway/cmd/app/main.go:32
